# QuickenPrices Configuration: config.yaml

# Tickers to track
  
tickers:
  "0P00013P6I.L": "HSBC FTSE All-World Index C Acc (GBp)"
  "0P00018XAP.L": "Vanguard FTSE 100 Idx Unit Tr £ Acc (GBp)"
  "AMGN":         "Amgen Inc. (USD)"
  "BZG25.NYM":    "Brent Crude Oil Last Day Finance (USD)"
  "CUKX.L":       "iShares VII PLC - iShares Core FTSE 100 ETF GBP Acc (GBp)"
  "CYSE.L":       "WisdomTree Cybersecurity UCITS ETF USD Acc (GBp)"
  "ELIX.L":       "Elixirr International plc (GBp)"
  "^FTAS":        "FTSE All-share (GBP)"
  "^FTSE":        "FTSE 100 (GBP)"
  "GLTA.L":       "Invesco UK Gilts UCITS ETF (GBp)"
  "GCG25.CMX":    "Gold (USD)"
  "HMWO.L":       "HSBC MSCI World UCITS ETF (GBp)"
  "IHCU.L":       "iShares S&P 500 Health Sector UCITS ETF USD (Acc) (GBp)"
  "IIND.L":       "iShares MSCI India UCITS ETF USD Acc (GBP)"
  "IUIT.L":       "iShares S&P 500 IT Sector UCITS ETF USD (Acc) (USD)"
  "SEE.L":        "Seeing Machines Limited (GBp)"
  "^OEX":         "S&P 100 INDEX (USD)"
  "^GSPC":        "S&P 500 INDEX (USD)"
  "VHVG.L":       "Vanguard FTSE Devel World UCITS ETF USD Acc (GBP)"
  "VNRX":         "VolitionRX Limited (USD)"
  "VUKG.L":       "Vanguard FTSE 100 UCITS ETF GBP Acc (GBP)"

# Application Paths - data files, logs, cache and quicken executable
paths:
  base: "C:\\Users\\wayne\\OneDrive\\Documents\\GitHub\\Python\\Projects\\quicken_prices\\"
  quicken: C:\\Program Files (x86)\\Quicken\\qw.exe
  data_file: data.csv # Data file 
  log_file: prices.log # Log file 
  cache: cache # Directory for cache

# Data period to collect in years (0.08 years ≈ 1 month,0.08 * 365 ≈ 29.2 days)
collection:
  period_years: 15
  max_retries: 3
  retry_delay: 2

# Default data collection periods for each quoteType:
default_periods:
  EQUITY: 5d
  ETF: 5d
  MUTUALFUND: 1mo
  FUTURE: 5d
  CURRENCY: 5d
  INDEX: 5d

# Cache Settings
cache:
  max_age_days: 30
  cleanup_threshold: 200

# Yahoo API Settings
api:
  rate_limit:
    max_requests: 30
    time_window: 60 # seconds

# Memory Management
memory:
  max_memory_percent: 75
  chunk_size: 1000

logging:
  levels:
    file: DEBUG
    terminal: DEBUG