# QuickenPrices Configuration: config.yaml

# Tickers to track
tickers:
  - 0P00013P6I.L
  - 0P00018XAP.L
  - AMGN
  - BZ=F
  - GC=F
  - CUKX.L
  - CYSE.L
  - ELIX.L
  - ^FTAS
  - ^FTSE
  - GLTA.L
  - HMWO.L
  - IHCU.L
  - IIND.L
  - IITU.L
  - SEE.L
  - ^OEX
  - ^GSPC
  - VHVG.L
  - VNRX
  - VUKG.L
  - EURGBP=X
  - MCHI
  - KAP.IL

home_currency: GBP

#  Data period to collect in years (0.08 years ≈ 1 month,0.08 * 365 ≈ 29.2 days)
collection_period_years: 0.16 

retries:
  max_retries: 5
  retry_delay: 5
  backoff: 2


# Logging levels for terminal and logfile: "DEBUG", "INFO", "WARNING", "ERROR", "TEXT"
logging_level:
  file: INFO
  terminal: INFO


log_file:
  max_bytes: 5242880
  backup_count: 5


# Application Paths - data files, logs, cache and quicken executable
paths:
  data_file: data.csv 
  log_file: prices.log 
  cache: cache 


# Cache Settings
cache:
  max_age_days: 150 
