# QuickenPrices Configuration: config.yaml

use_simulator: false # Set to 'false' to use the real API

# Tickers to track
  
tickers:
  0P00013P6I.L:  "HSBC FTSE All-World Index C Acc (GBP)"
  0P00018XAP.L:  "Vanguard FTSE 100 Idx Unit Tr £ Acc (GBP)"
  AMGN:          "Amgen Inc. (USD)"
  BZ=F:          "Brent Crude Oil Last Day Finance (USD)"
  CUKX.L:        "iShares VII PLC - iShares Core FTSE 100 ETF GBP Acc (GBP)"
  CYSE.L:        "WisdomTree Cybersecurity UCITS ETF USD Acc (GBP)"
  ELIX.L:        "Elixirr International plc (GBP)"
  EURGBP=X:      "EUR/GBP Fx"
  fake:          "fake"
  ^FTAS:         "FTSE All-share (GBP)"
  ^FTSE:         "FTSE 100 (GBP)"
  GBP=X:         "USD/GBP Fx"
  GL1S.MU:       "Invesco Markets II Plc - Invesco UK Gilt UCITS ETF (EUR)"
  GLTA.L:        "Invesco UK Gilts UCITS ETF (GBP)"
  GC=F:          "Gold (USD)"
  HMWO.L:        "HSBC MSCI World UCITS ETF (GBP)"
  IHCU.L:        "iShares S&P 500 Health Care Sector UCITS ETF USD (Acc) (GBP)"
  IIND.L:        "iShares MSCI India UCITS ETF USD Acc (GBP)"
  IUIT.L:        "iShares S&P 500 Information Technology Sector UCITS ETF USD (Acc) (USD)"
  LAU.AX:        "(AUD)"
  SEE.L:         "Seeing Machines Limited (GBP)"
  ^OEX:          "S&P 100 INDEX (USD)"
  ^GSPC:         "S&P 500 INDEX (USD)"
  SQX.CN:        "(CAD)"
  VHVG.L:        "Vanguard FTSE Developed World UCITS ETF USD Accumulation (GBP)"
  VNRX:          "VolitionRX Limited (USD)"
  VUKG.L:        "Vanguard FTSE 100 UCITS ETF GBP Accumulation (GBP)"

# Debug Configuration -  populated for testing specific tickers
debug:
  - VHVG.L
  - ELIX.L
  - VNRX
  - EURGBP=X
  - GC=F

# Application Paths - data files, logs, cache and quicken executable
paths:
  base: C:\Users\wayne\OneDrive\Documents\GitHub\Python\Projects\quicken_prices\
  quicken: C:\Program Files (x86)\Quicken\qw.exe
  data_file: data.csv # Data file 
  log_file: prices.log # Log file 
  cache: cache # Directory for cache

# Data period to collect in years (0.08 years ≈ 1 month,0.08 * 365 ≈ 29.2 days)
collection:
  period_years: 0.08
  max_retries: 3
  retry_delay: 2

# Default data collection periods for each quoteType:
default_periods:
  EQUITY: 5d
  ETF: 1mo
  MUTUALFUND: 1mo
  FUTURE: 5d
  CURRENCY: 5d
  INDEX: 5d

# Cache Settings
cache:
  max_age_hours: 168 # 1 week
  cleanup_threshold: 200

# Yahoo API Settings
api:
  rate_limit:
    max_requests: 30
    time_window: 60 # seconds

# Memory Management
memory:
  max_memory_percent: 75
  chunk_size: 1000

# Data Validation
validation:
  required_columns:
    - Ticker
    - Close
    - Date

logging:

  # Levels reported in each place. 
  # ERROR - Indicates a serious problem that prevents the program from executing correctly
  # WARNING - Indicates a potential issue that may lead to problems in the future
  # INFO - Useful for understanding the program's behavior and for auditing purposes
  # DEBUG - For detailed information to trace the execution flow of a program
  # These are hierarchial levels. Python scores them as ERROR=40, WARNING=30, INFO=20, DEBUG=10. So selecting a lower level includes all higher levels too.

  levels:
    file: DEBUG
    terminal: DEBUG

  message_formats:

    file:
        error: '%(asctime)s %(levelname)s: %(filename)s:%(lineno)d - %(message)s - %(exc_info)s'
        warning: '%(asctime)s %(levelname)s: %(filename)s:%(lineno)d - %(message)s'
        info: '%(asctime)s %(levelname)s: %(message)s'
        debug: '%(asctime)s %(levelname)s: %(filename)s:%(lineno)d - %(message)s - %(funcName)s - %(module)s - %(process)d - %(thread)d - %(relativeCreated)d - %(threadName)s'
      
    terminal:
        error: '%(levelname)s: %(filename)s:%(lineno)d - %(message)s - %(exc_info)s'
        warning: '%(levelname)s: %(filename)s:%(lineno)d - %(message)s'
        info: '%(levelname)s: %(message)s'
        debug: '%(levelname)s: %(filename)s:%(lineno)d - %(message)s'

  colors:
    error: red
    warning: yellow
    info: green
    debug: blue

  max_bytes: 5242880
  backup_count: 5