# QuickenPrices Configuration: config.yaml

home_currency: GBP
collection:
  period_years: 0.08
  max_retries: 3
  retry_delay: 2


# Logging levels for terminal and logfile: "DEBUG", "INFO", "WARNING", "ERROR", "TEXT"
logging:
  levels:
    file: DEBUG
    terminal: DEBUG
  max_bytes: 5242880
  backup_count: 5

# Tickers to track
tickers:
  - 0P00013P6I.L
  - 0P00018XAP.L
  - AMGN
  - BZG25.NYM
 
# Data period to collect in years (0.08 years ≈ 1 month,0.08 * 365 ≈ 29.2 days)
period_years: 0.08


# Application Paths - data files, logs, cache and quicken executable
paths:
  quicken: C:\Program Files (x86)\Quicken\qw.exe
  data_file: data.csv # Data file 
  log_file: prices.log # Log file 
  cache: cache # Directory for cache

# Show startup initiation process
clear_startup: False

# Cache Settings
cache:
  max_age_days: 30
  cleanup_threshold: 200
