# QuickenPrices Configuration: config.yaml

# Tickers to track
tickers:
  # - 0P00013P6I.L
  # - 0P00018XAP.L
  - AMGN
  # - BZG25.NYM
  # - CUKX.L
  # - CYSE.L
  # - ELIX.L
  # - ^FTAS
  # - ^FTSE
  # - GLTA.L
  # - GCG25.CMX
  # - HMWO.L
  # - IHCU.L
  # - IIND.L
  # - IUIT.L
  # - SEE.L
  # - ^OEX
  # - ^GSPC
  # - VHVG.L
  # - VNRX
  # - VUKG.L

home_currency: GBP

#  Data period to collect in years (0.08 years ≈ 1 month,0.08 * 365 ≈ 29.2 days)
collection_period_years: 0.04

retries:
  max_retries: 3
  retry_delay: 2
  backoff: 2


# Logging levels for terminal and logfile: "DEBUG", "INFO", "WARNING", "ERROR", "TEXT"
logging_level: 
  file: DEBUG 
  terminal: INFO
  

log_file:
  max_bytes: 5242880
  backup_count: 5
 

# Application Paths - data files, logs, cache and quicken executable
paths:
  data_file: data.csv # Data file name 
  log_file: prices.log # Log file name 
  cache: cache # Directory for cache


# Cache Settings
cache:
  max_age_days: 30